### ISSUE TITLE
Could you please add links to other vue related implementations?

### ISSUE THREAD

**Issue by levchak0910** [devJang/nuxt-realworld#1]
The goal of this to have all implementations linked with each other

Other implementations:
https://github.com/gothinkster/vue-realworld-example-app - vue2, js
https://github.com/AlexBrohshtut/vue-ts-realworld-app - vue2, ts, class-component
https://github.com/mutoe/vue3-realworld-example-app - vue3, vite, ts, composition api
https://github.com/levchak0910/vue3-ssr-realworld-example-app - vue3, ssr

**Comment by pocojang** [comment]
Good idea!

https://github.com/devJang/nuxt-realworld/commit/38c0d3c1e7d8abec63e48e46dd5326ae695873a9
